trying to figure the regex out

diff --git a/scraper b/scraper
--- a/scraper
+++ b/scraper
@@ -1,6 +1,6 @@
 #!/bin/bash  
 #  Author: Sergio "Checo" Gonzales
-#  Date: 07-11-2016
+#  Date: 07-10-2016
 #  This can be used to scrape the backpage.com
 CATEGORY="$1,"
 DATE=`date +%d-%m-%Y`
@@ -9,93 +9,76 @@ PAGE=1
 #  If directories do not exist, create them.
 
 if [ -z "$1" ]; then
-	echo "Error: Posting category or categories not given without defulat"
-	echo "Usage: $0 [category,category,...] [geography] [geography] ..."
-	exit 1
+ echo "Error: Posting category or categories not given without defulat"
+ echo "Usage: $0 [category,category,...] [geography] [geography] ..."
+ exit 1
 fi
 
 if [ -z "$2" ]; then
-	echo "Error: Geography or georgraphies not given without default"
-	echo "Usage: $0 [category,category,...] [geography] [geography] ..."
-	exit 1 
+ echo "Error: Geography or georgraphies not given without default"
+ echo "Usage: $0 [category,category,...] [geography] [geography] ..."
+ exit 1 
 fi
-if [ ! -d ./content ]; then
-	mkdir ./content
+
+if [ ! -d ./URLS/non-sponsored ]; then
+ mkdir -p ./URLS/non-sponsored
 fi
-if [ ! -e ./content/posting_content_raw.csv -o -s ./content/posting_content_raw.csv ]; then
-	echo TITLE,DATE,TIME,BODY,AGE,LOCATION,OTHER_POSTING,IMG_PATH > ./content/posting_content_raw.csv
+if [ ! -d ./URLS/sponsored ]; then
+ mkdir -p ./URLS/sponsored
 fi
+if [ ! -d ./.pages/"$DATE" ]; then
+ mkdir -p ./.pages/"$DATE"
+fi
+
 #  Select geographies.. not sure how to implement this yet
 
 #  Scrape topics
 until [ -z "$2" ]; do
-	SPATH=./URLs/sponsored/"$2"
-	NSPATH=./URLs/non-sponsored/"$2"
-	PPATH=./.pages/"$2"/"$DATE"
-	CPATH=./content/"$2"/
-	IPATH=./images/"$2"/
 
 #  Download URLS and check remove URLS previously downloaded
 #  Still need to implement for subsequent pages
 	for X in `eval echo {$CATEGORY}`; do
 		PAGE=1
-		FNAME="$2"_"$X"_"$DATE"
-
-		if [ ! -d "$NSPATH"/"$X" ]; then
-			mkdir -p "$NSPATH"/"$X"
-		fi
-		if [ ! -d "$SPATH"/"$X" ]; then
-			mkdir -p "$SPATH"/"$X"
-		fi
-		if [ ! -d "$PPATH"/"$X" ]; then
-			mkdir -p "$PPATH"/"$X"
-		fi
-		if [ ! -d "$CPATH"/"$X" ]; then
-			mkdir -p "$CPATH"/"$X"
-		fi
-		if [ ! -d "$IPATH"/"$X" ]; then
-			mkdir -p "$IPATH"/"$X"
-		fi	
-		
 		until [ "$PAGE" -gt 444 ]; do
-			if [ 0 -eq 0 ]; then
-				echo downloading URLs for "$2"/"$X"/page"$PAGE"
-			fi
+			FNAME="$2"_"$X"_"$DATE"
    
-			curl -s "$2".backpage.com/"$X"/"&page=$PAGE" > "$PPATH"/"$X"/"$FNAME"_pg"$PAGE".html
+			curl -s "$2".backpage.com/"$X"/"&page=$PAGE" > ./.pages/"$DATE"/"$FNAME"_pg"$PAGE".html
    #  Test to see if the posting pages has ended and there are "No more matches."
-			grep -q "<div><b>No matches found.</b><br><br></div>" "$PPATH"/"$X"/"$FNAME"_pg"$PAGE".html
+			grep -s "<div><b>No matches found.</b><br><br></div>" ./.pages/"$DATE"/"$FNAME"_pg"$PAGE".html
 			if [ $? -eq 0 ]; then
-				echo No more posting at page: "$PAGE".
+				echo No more posting at page: "$PAGE". "$2"_"$X" completed.
 				break
 			fi
    #  Find every posting and sponsord URLs on currnet page
-			grep -v "sponsorBoxPlusImages" "$PPATH"/"$X"/"$FNAME"_pg"$PAGE".html | grep -o /"$X"/[a-z\-]*/[0-9]* | sort | uniq > "$NSPATH"/"$X"/"$FNAME"_temp.txt
-			grep "sponsorBoxPlusImages" "$PPATH"/"$X"/"$FNAME"_pg"$PAGE".html | grep -o /"$X"/[a-z\-]*/[0-9]* | sort | uniq > "$SPATH"/"$X"/"$FNAME"_ads_temp.txt
+#			grep -o http://[a-z]*.backpage.com/"$category"/[a-z\-]*/[0-9]* ./.pages/"$FNAME"_pg"$PAGE".html | uniq > ./URLS/"$FNAME"_temp.txt
+			grep -o /"$X"/[a-z\-]*/[0-9]* ./.pages/"$DATE"/"$FNAME"_pg"$PAGE".html | sort | uniq > ./URLS/"$FNAME"_temp.txt
+			grep "sponsorBoxPlusImages" ./.pages/"$DATE"/"$FNAME"_pg"$PAGE".html | grep -o /"$X"/[a-z\-]*/[0-9]* | sort | uniq > "$FNAME"_ads_temp.txt
 
-     			if [ `ls -1 "$NSPATH"/"$X" | wc -l` -le 1 ]; then 
-       				mv "$NSPATH"/"$X"/"$FNAME"_temp.txt "$NSPATH"/"$X"/"$FNAME".txt
+     			if [ `ls ./URLS/ | grep -c "$2"[a-z,_]*"$X"` -le 1 ]; then 
+       				mv ./URLS/"$FNAME"_temp.txt ./URLS/non-sponsored/"$FNAME".txt
      			else
-       				sort -u `ls -d  "$NSPATH"/"$X"/*` > "$NSPATH"/"$X"/"$FNAME".txt
-       				rm "$NSPATH"/"$X"/"$FNAME"_temp.txt
+       				sort -u `ls ./URLS/"$2"* | grep "$X"` > ./URLS/non-sponsored/"$FNAME".txt
+       				rm ./URLS/"$FNAME"_temp.txt
      			fi
-			if [ `ls -1 "$SPATH"/"$X" | wc -l` -le 1 ]; then
-				mv "$SPATH"/"$X"/"$FNAME"_ads_temp.txt "$SPATH"/"$X"/"$FNAME"_sponsored.txt
+			if [ `ls ./URLS/ | grep -c "$2"[a-z,_]*"$X"` -le 1 ]; then
+				mv ./URLS/"$FNAME"_ads_temp.txt ./URLS/sponsored/"$FNAME"_sponsored.txt
 			else
-				sort -u `ls -d "$SPATH"/"$X"/*` > "$SPATH"/"$X"/"$FNAME"_sponsored.txt
-    				rm "$SPATH"/"$X"/"$FNAME"_ads_temp.txt
+				sort -u `ls ./URLS/ | grep "$X"` > ./URLS/sponsored/"$FNAME"_sponsored.txt
+    				rm ./URLS/"$FNAME"_ads_temp.txt
 			fi
+
 			
     			((PAGE+=1))
 		done 
-#  Download and organize content
-		echo downloading sponsored content for "$2"/"$X"
-		while read URL; do
-			
-		done < "$SPATH"/"$X"/"$FNAME"_sponsored.txt
 	done
 	shift
 done
+
+#  Record ads that are paid advertisment and remove duplicates
+#+ from other URL lists
+
+
+#  Download and organize content
 
 
 exit $?
